server:
  port: 8082

spring:

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/maintainx_resident}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 6MB

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: resident-service-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

document:
  upload-dir: ${DOCUMENT_UPLOAD_DIR:uploads}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
